### ISSUE TITLE
ERROR: cannot find role in /roles/silpion.util ...

### ISSUE THREAD

**Issue by ssbarnea** [silpion/ansible-etckeeper#8]
ERROR: cannot find role in /roles/silpion.util ...
It seems that ansible-galaxy install command does not install requirements and you end-up being unable to apply the role.

**Comment by spul** [comment]
Hi,
would you mind telling me what you did to download/install etckeeper role in your playbook? etckeeper role has requirements.yml and ansible.cfg configured to install groover.util role as silpion.util in the same directory where etckeeper role lives.

So, if you cd to etckeeper role and run ``ansible-galaxy install -r requirements.yml``, silpion.util should be available in ../silpion.util.
If your playbook finds etckeeper role, it should find silpion.util role as well.

**Comment by ssbarnea** [comment]
Sorry but galaxy is able to install role dependencies itself, and there is only one correct way to install a galaxy role:
```
ansible-galaxy install groover.etckeeper
```
And this fails with your role because galaxy is unable to find:
```
- groover.etckeeper was installed successfully
[DEPRECATION WARNING]: The comma separated role spec format, use the yaml/explicit format instead.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
- adding dependency: silpion.util
- downloading role 'util', owned by silpion
 [WARNING]: - silpion.util was NOT installed successfully: - sorry, silpion.util was not found on https://galaxy.ansible.com.
```

**Comment by c-j-s** [comment]
Yes, I have the same issue. It would be nice if this Just Worked with `ansible-galaxy install groover.etckeeper`.  Or is that not your official role in Ansible Galaxy?
